Repository wecode-bootcamp-korea/48-2nd-5ronaminC-backend, pull requests merged in 2023-08, with the labels that each got.

#2 Add: Layered Pattern complete
  api/models/dataSource.js
  api/models/index.js
  api/routes/index.js
  api/utils/auth.js
  api/utils/error.js
  app.js
Labels: 멘토 리뷰 요청

#3 [5ronaminC팀] DataBase 작업
  db/migrations/20230823035512_create_preferred_stores_table.sql
  db/migrations/20230823035849_create_users_table.sql
  db/migrations/20230823052811_create_colors_table.sql
  db/migrations/20230823053538_create_category_spaces_table.sql
  db/migrations/20230823053555_create_category_types_table.sql
  db/migrations/20230823053955_create_size_options_table.sql
  db/migrations/20230823054007_create_coordinates_table.sql
  db/migrations/20230823054020_create_products_table.sql
  db/migrations/20230823054033_create_product_images_table.sql
  db/migrations/20230823054045_create_showroom_images_table.sql
  db/migrations/20230823054056_create_reviews_table.sql
  db/migrations/20230823054131_create_carts_table.sql
  db/migrations/20230823054142_create_wishlists_table.sql
  db/migrations/20230823054152_create_order_status_codes_table.sql
  db/migrations/20230823054203_create_orders_table.sql
  db/migrations/20230823054215_create_order_items_table.sql
  db/migrations/20230823054226_create_payment_information_table.sql
Labels: 멘토 리뷰 요청

#4 FIX : modify DB wishlists table
  db/migrations/20230824045826_modify_wishlists_table.sql
Labels: 멘토 리뷰 요청

#5 Add : signUp settings complete
  api/controllers/index.js
  api/controllers/userController.js
  api/models/index.js
  api/models/userDao.js
  api/routes/index.js
  api/routes/userRouter.js
  api/services/index.js
  api/services/userService.js
  api/utils/validator.js
  app.js
Labels: 멘토 리뷰 요청, 수정 요청

#7 Add:signin complete
  api/controllers/userController.js
  api/models/userDao.js
  api/routes/userRouter.js
  api/services/userService.js
  api/utils/validator.js
Labels: 멘토 리뷰 요청

#8 Modify : signin modified
  .env.sample
  api/models/userDao.js
Labels: 멘토 리뷰 요청, 수정 요청

#6 [5ronaminC] wishlist_DB에 DATA INSERT 기능 구현
  api/controllers/index.js
  api/controllers/wishController.js
  api/models/index.js
  api/models/wishDao.js
  api/routes/index.js
  api/routes/wishRouter.js
  api/services/index.js
  api/services/wishService.js
  app.js
Labels: 멘토 리뷰 요청

#9 [5ronaminC] wishrouter에 인가 기능 추가
  api/controllers/wishController.js
  api/routes/wishRouter.js
Labels: 멘토 리뷰 요청

#10 장바구니 기능 구현 추가
  api/controllers/cartController.js
  api/controllers/index.js
  api/models/cartDao.js
  api/models/index.js
  api/routes/cartRouter.js
  api/routes/index.js
  api/services/cartService.js
  api/services/index.js
Labels: 수정 요청

#13 결제 정보 불러오기
  api/controllers/index.js
  api/controllers/orderController.js
  api/models/index.js
  api/models/orderDao.js
  api/routes/index.js
  api/routes/orderRouter.js
  api/services/index.js
  api/services/orderService.js
Labels: 멘토 리뷰 요청

#14 [5ronaminC] modify 장바구니 insert 기능 내용 수정
  api/controllers/cartController.js
  api/models/cartDao.js
  api/routes/cartRouter.js
  api/services/cartService.js
Labels: 멘토 리뷰 요청

#16 [5ronaminC]modify orders table
  db/migrations/20230831025155_modify_order_items_table.sql
  db/migrations/20230831025342_modify_payment_information_table.sql
  db/migrations/20230831025835_modify_orders_table.sql
  db/migrations/20230831030452_modify_order_items_table.sql
  db/migrations/20230831030518_modify_payment_information_table.sql
Labels: 멘토 리뷰 요청

#15 Add: mainpage complete
  api/controllers/index.js
  api/controllers/showroomController.js
  api/models/index.js
  api/models/showroomDao.js
  api/routes/index.js
  api/routes/showroomRouter.js
  api/services/index.js
  api/services/showroomService.js
  api/services/userService.js
  api/utils/shippingFee.js
  api/utils/validator.js
Labels: Conflict 해결 요청, 멘토 리뷰 요청, 수정 요청

#11 장바구니 리스트 불러오기
  .env.sample
  api/controllers/cartController.js
  api/controllers/index.js
  api/models/cartDao.js
  api/routes/cartRouter.js
  api/services/cartService.js
  api/utils/shippingFee.js
Labels: 멘토 리뷰 요청, 완료

#12 장바구니 상품 삭제
  api/controllers/cartController.js
  api/models/cartDao.js
  api/routes/cartRouter.js
  api/services/cartService.js
  app.js
Labels: 완료

#17 Modify: final mainpage modified
  api/controllers/userController.js
  api/models/userDao.js
  api/services/userService.js
  api/utils/validator.js
Labels: 멘토 리뷰 요청

#18 [5ronaminC] 제품 상세 페이지 기능 구현
  api/controllers/index.js
  api/controllers/productController.js
  api/models/index.js
  api/models/productDao.js
  api/routes/index.js
  api/routes/productRouter.js
  api/services/index.js
  api/services/productService.js
Labels: 멘토 리뷰 요청

#20 결제 후 주문내역 업데이트
  api/controllers/orderController.js
  api/models/orderDao.js
  api/routes/orderRouter.js
  api/services/orderService.js
  package-lock.json
  package.json
Labels: 멘토 리뷰 요청
